### PR TITLE
Schedule Occurrences should take large overlapping occurrences into account

### PR DESCRIPTION
**Pull request by Ravenstine**
#419 

The initial implementation of schedule occurrence problem detection had an issue with occurrences that would overlap multiple occurrences, including ones that were intended to overlap like special coverage.  

I decided to tread gaps and overlaps a bit different this time.  Overlaps iterate per-occurrence rather than per-pair(i.e. each_cons), and ignore non-recurring occurrences that overlap.  The preview in Outpost will show a list of occurrences that an occurrence is overlapping.  The occurrence it chooses is the larger one, or the earliest one if they are the same length, so we don't end up with duplicate listings.

The way that gaps are handled isn't too different from how they were previously, except the array of occurrences is "flattened" so that overlaps are eliminated and only gaps or a completely congruent schedule can be iterated over.

### CODE REVIEW

**Comment by Ravenstine** [comment]
@sdillingham I'll keep what I've got on staging for a while if you want to play around and give any feedback.

**Comment by sdillingham** [comment]
Hey @Ravenstine, I'm getting 500 errors on staging when I try to view conflicts on a recurring rule. Any thoughts about what the issue might be?

**Comment by Ravenstine** [comment]
@sdillingham Give it another try now.  I don't know what changed after I deployed another branch earlier today and re-deployed this one.

**Comment by sdillingham** [comment]
Thanks, it's working now. I'm noticing time zone discrepancies between what's listed in the schedule occurrences table view in Outpost and the Show Conflicts popup; not sure if that's a symptom of staging or not.

**Pull request merged**
