### PR TITLE
Remove social counts for Facebook and Twitter.

### PR DESCRIPTION
**Pull request by Ravenstine**
#366

I've removed the JavaScript and HTML relating to Facebook and Twitter social counts.

### CODE REVIEW

**Comment by sdillingham** [comment]
Functionally this looks good @Ravenstine, and I think you caught all the templates where we had markup to remove. A couple minor edits:

The `twiturl` option in the scpr.SocialTools class is no longer used, and can be removed:

https://github.com/SCPR/SCPRv4/pull/375/files?diff=unified#diff-f69e34f5df6c22bc6b3c7aa39f45fc7bR124

Originally, we were setting the `fburl` option to default to Facebooks FQL endpoint:

https://github.com/SCPR/SCPRv4/pull/375/files?diff=unified#diff-f69e34f5df6c22bc6b3c7aa39f45fc7bL123

But since we're not using that endpoint anymore to get FB share counts, that default doesn't make sense. Now `fburl` is only being set to wire up the sharing functionality:

https://github.com/SCPR/SCPRv4/pull/375/files?diff=unified#diff-f69e34f5df6c22bc6b3c7aa39f45fc7bL166

Maybe there's a more sensible default for `fburl` given the way we're using it?

It's a small detail, but this comment should be updated to remove the reference to "fetch(ing) share counts" since we're not doing that anymore:
  
https://github.com/SCPR/SCPRv4/pull/375/files?diff=unified#diff-f69e34f5df6c22bc6b3c7aa39f45fc7bL134

**Comment by Ravenstine** [comment]
@sdillingham Taking a further look, I can't come up with a more sensible value for `fburl` variable since the other uses of facebook.com urls require a specific scope.  Thanks for catching those details that need to be changed.

**Comment by sdillingham** [comment]
:+1:

**Comment by sdillingham** [comment]
Looks good @Ravenstine. This is ready to :shipit:.

**Pull request merged**
