### PR TITLE
NPM install Javascript packages on deployment

### PR DESCRIPTION
**Pull request by Ravenstine**
#474 

Most of our vendor JS assets have been removed from our repo and are now installed using `npm install` into the `node_modules` directory.  Browserify is also included, though is only currently used with moment-strftime(it is exported as a module rather than as a global).  The rest of our vendor javascripts are still required through Sprockets, but from the `npm_modules` directory.

A task has been added to `lib/tasks/deploybot.rake` which gets triggered by Deploybot on deployments.  This allows us to run `npm install`, and would allow us to run other project-specific tasks on deployment if we ever needed to.  Other Rails projects that aren't using NPM will still deploy normally.

### CODE REVIEW

**Comment by Ravenstine** [comment]
@sdillingham I can see what you mean if we aren't using Handlebars in our actual codebase.  Do you still think it's acceptable to keep requiring it if we continue to use it with Outpost.Autosave?  Though it's only one instance of its use, I'd actually prefer Handlebars over Eco(which is being used by Outpost and is coming from it).  As much I adore CoffeeScript, Eco depends on CoffeeScript whilst Handlebars works with both, but is far more logic-less than Eco.

Does that make sense, or do you think we should still use Eco across the board?

**Comment by sdillingham** [comment]
I think using/including Handlebars is fine for the autosave work.

**Comment by Ravenstine** [comment]
Sweet.

**Comment by Ravenstine** [comment]
@sdillingham Here's an update that I did on the packages I specified:

```
    fastclick           - 0.6.11         -> 0.6.11
    handlebars          - 1.0.0.beta.6   -> 1.0.2-beta
    history             - ???            -> 2.0.1
    jquery-ajax-xdomain - 1.0.4          -> 1.0.4
    jplayer             - 2.2.0          -> 2.8.4
    moment-strftime     - ???            -> 0.1.5
    moment-twitter      - ???            -> 0.2.0
    selectivizr         - 1.0.3b         -> 1.0.3
    swfobject           - 2.2            -> 2.2
    windowtamer         - ???            -> ???
    x2json              - 1.1.5          -> 2.2.0
    jquery-scrolldepth  - 0.9            -> 0.9.1
```

History and and moment-* had no version information.  Though I've confirmed that both the new versions of moment-strftime and moment-twitter work as expected.  Windowtamer never seems to have had a version number, but it was also last updated in 2012 which makes me doubt that the latest version is much different than what we already have.  Jquery-scrolldepth was minor bumped because that's been modified and forked for our own purposes.  Other version changes were the closest versions I could get to with NPM.

**Pull request closed without merging**
