### PR TITLE
File name sanitize

### PR DESCRIPTION
**Pull request by Ravenstine**
Addresses issues #263.

If a "safe_filename" input is included inside a form, the SafeFilename middleware finds any key in the form that matches "filename" and with the value replaces whitespaces with underscores and accented characters with their simple equivalents.

### CODE REVIEW

**Comment by ewr** [comment]
Why do we care to be able to turn this on/off in the form? Wouldn't turning it off still just cause it to fail to upload?

**Comment by Ravenstine** [comment]
I added the ability to toggle it so that we aren't recursively searching a form hash every time we submit a form that doesn't have file names or uploads of any kind.  Not that it's that big a deal since it's only on submits and the form hash is never very deep.  If we don't care about this, then we don't need the on/off aspect.

**Comment by ewr** [comment]
I don't believe this does anything for #248. That's a form validation issue, not an upload issue.

I believe we would just want this applied to any uploads. I'm not a fan of that being something the form itself deals with, but potentially it could be via specifying a path in a config file or something like that if you think it's necessary for performance.

**Comment by Ravenstine** [comment]
I mistakenly believed that issue had to do with the file upload.

I would not mind omitting the switch all-together if we want this functionality to apply to all(or most) of our forms; if there ever comes a time where we don't want the file name to be sanitized, perhaps it would be better to specify a blacklist of paths in a config file.  Performance would only be an issue when someone submits a form, and any difference in performance would probably be imperceptible.  Sometimes I'm overly-cautious.

**Pull request merged**
