### PR TITLE
Refine tag implementation

### PR DESCRIPTION
**Pull request by Ravenstine**
#381

One part of this I think might need to be changed is the way that the `tag types` are implemented.  Initially, I went with just a string value but convinced myself that this needed to be a relation because of the way that simple_form creates the select field(which expects a collection of type objects that contain their respective tags).  But now that I've gotten to this point, I believe this is likely unnecessary since it doesn't seem like we are changing these types often(or at all?).  This would be a simple change, especially since that's how it worked in earlier commits.

While I added the ability to select a parent program from the Tag edit view, I also left the tag association selection in the Program edit view.  I'm not sure if we need to get rid of the latter, but we certainly could if that seems too hazardous.

I removed the `pry-byebug` gem because not only is it not necessary but it often slows down the development environment significantly.

### CODE REVIEW

**Comment by Ravenstine** [comment]
@sdillingham @ewr Do you guys have an opinion on whether or not the tag groups should just be string fields or should be associative?  

The only reason I ask is because I ended up changing it to be associative to fulfill the way that simple_form creates grouped selects, even though it can be worked around.

`f.association :tags, as: :grouped_select, collection: TagType.all, group_method: :tags, input_html: { :multiple => true }`

**Comment by sdillingham** [comment]
I'm not sure I see the benefit to tag type being its own model with an association. Why not use a constant like this:

https://github.com/SCPR/SCPRv4/blob/master/app/models/news_story.rb#L43-L55

**Comment by sdillingham** [comment]
In general I don't want to make decisions about how we model data that are influenced by how things like simple_form behave.

**Comment by Ravenstine** [comment]
Cool, I think I agree. :+1:

**Comment by Ravenstine** [comment]
@sdillingham So I've made some changes based on my last question, and I've put the work up on staging.  I have also gotten rid of the tag selection in the KpccProgram edit view since it does seem better to just select the parent in the Tag view.

**Comment by Ravenstine** [comment]
@sdillingham @ewr There's some peculiar behavior that's left me stumped.

On my machine, both the `tag_type` and `parent` fields save properly upon edit.

Yesterday, on Sean's machine, neither field would save.  No failure would occur; the values just don't persist.

On staging, for some weird reason, the migrations seemed to have run but the database still had an older field name for `tag_type` (which was `tag_type_id`).  A migration takes care of that name change but even when I rolled back and re-migrated, I'd get the same issue.  But I'm digressing a little, since that problem has been resolved.

Now that the code is now running on staging, the `tag_type` field never seems to persist, but the `parent` field seems to persist about 60% of the time.

I can't figure out why this would be, since the changes to make these features happen were adding the fields to the table, defining the columns in `Outpost::TagsController`, and using the form helpers in the view to create the right select tags.  The option tags in the select appear to have the correct values.

I'm not sure what's going on here.

**Pull request closed without merging**
